print("Mad Lib")

adjective_1 = input("What is an adjective? ")
adjective_2 = input("What is another adjective? ")
adjective_3 = input("What is another adjective? ")
noun_1 = input("What is a noun? ")
noun_2 = input("What is another noun? ")
noun_3 = input("What is another noun? ")
noun_4 = input("What is another noun? ")
noun_5 = input("What is another noun? ")
bodypart_1 = input("WHat is a body part? ")
bodypart_2 = input("What is another body part? ")

print("The monster under my bed is %s" % adjective_1)
print("The monster made me feel %s" % adjective_2)
print("The monster was very %s" % adjective_3)
print("The mosnter had a very tall %s" % noun_1)
print("The monster first went into the big scary %s" % noun_2)
print("I got very scared and ran into a %s" % noun_3)
print("")